import { router } from 'expo-router';
import React from 'react';
import { View } from 'react-native';
import { when } from '../../lib/format';
import { Row as R } from '../../lib/types';
import { useApi } from '../../lib/useApi';
import { colors } from '../theme';
import { Badge, Card, ErrorView, Loading, Muted, Row, Title } from '../ui';

export function BomRevisions({ siteId }: { siteId: string }) {
  const d = useApi<R[]>(`/bom/sites/${siteId}/revisions`);
  if (d.error) return <ErrorView error={d.error} onRetry={d.reload} />;
  if (!d.data) return <Loading />;
  return (
    <View>
      <Muted>REV 0 is the Ericsson tool export as received (locked). Generated revisions are editable while DRAFT.</Muted>
      {d.data.map((r) => (
        <Card key={r.BOM_REV_ID} onPress={() => router.push({ pathname: '/bom/[revId]', params: { revId: r.BOM_REV_ID } })}>
          <Row style={{ justifyContent: 'space-between' }}>
            <Title>{r.REV_LABEL}</Title>
            <Row><Badge text={r.STATUS} />{r.LOCKED ? <Badge text="locked" color={colors.muted} /> : null}</Row>
          </Row>
          <Muted>{`${r.KIND === 'TOOL_REV0' ? 'Received tool export' : 'Generated by ScopeIQ'} - ${when(r.CREATED_AT)}`}</Muted>
          {r.TOTALS ? <Muted>{`${r.TOTALS.lines ?? '-'} lines, ${r.TOTALS.install_qty ?? '-'} install / ${r.TOTALS.remove_qty ?? '-'} remove`}</Muted> : null}
        </Card>
      ))}
    </View>
  );
}
