-- =====================================================================================================
-- 01  Account objects: roles, warehouse, database, schemas, grants.   Run as: SECURITYADMIN + SYSADMIN
--     (or ACCOUNTADMIN for the POC). Idempotent.
-- =====================================================================================================
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS IDENTIFIER($SCOPEIQ_ADMIN_ROLE) COMMENT = 'ScopeIQ: owns objects, runs deployments';
CREATE ROLE IF NOT EXISTS IDENTIFIER($SCOPEIQ_APP_ROLE)   COMMENT = 'ScopeIQ: API and pipeline procedures';
CREATE ROLE IF NOT EXISTS IDENTIFIER($SCOPEIQ_READ_ROLE)  COMMENT = 'ScopeIQ: read-only reporting';
GRANT ROLE IDENTIFIER($SCOPEIQ_READ_ROLE) TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT ROLE IDENTIFIER($SCOPEIQ_APP_ROLE)  TO ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
GRANT ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE) TO ROLE SYSADMIN;
-- the deploying user works as the admin role in later scripts
EXECUTE IMMEDIATE 'GRANT ROLE ' || $SCOPEIQ_ADMIN_ROLE || ' TO USER "' || CURRENT_USER() || '"';

USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($SCOPEIQ_WH)
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ScopeIQ pipeline and API';
EXECUTE IMMEDIATE 'ALTER WAREHOUSE ' || $SCOPEIQ_WH || ' SET WAREHOUSE_SIZE = ' || $SCOPEIQ_WH_SIZE;
CREATE DATABASE IF NOT EXISTS IDENTIFIER($SCOPEIQ_DB) COMMENT = 'ScopeIQ scoping POC';
GRANT OWNERSHIP ON DATABASE IDENTIFIER($SCOPEIQ_DB) TO ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE) COPY CURRENT GRANTS;
GRANT USAGE, OPERATE ON WAREHOUSE IDENTIFIER($SCOPEIQ_WH) TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($SCOPEIQ_WH) TO ROLE IDENTIFIER($SCOPEIQ_READ_ROLE);

USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
CREATE SCHEMA IF NOT EXISTS RAW   COMMENT = 'Landing: staged documents, SiteTracker exports, parsed documents';
CREATE SCHEMA IF NOT EXISTS REF   COMMENT = 'Versioned reference data: catalog, kit rules, rules, rate card, personas, workflow';
CREATE SCHEMA IF NOT EXISTS CORE  COMMENT = 'Pipeline results and business records';
CREATE SCHEMA IF NOT EXISTS WF    COMMENT = 'Workflow events, notifications, comments';
CREATE SCHEMA IF NOT EXISTS AUDIT COMMENT = 'Audit trail, application and error logs (append-only)';
CREATE SCHEMA IF NOT EXISTS APP   COMMENT = 'Procedures, tasks, reporting views';

GRANT USAGE ON DATABASE IDENTIFIER($SCOPEIQ_DB) TO ROLE IDENTIFIER($SCOPEIQ_READ_ROLE);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($SCOPEIQ_DB) TO ROLE IDENTIFIER($SCOPEIQ_READ_ROLE);
-- Reporting role: views only
GRANT SELECT ON FUTURE VIEWS IN SCHEMA APP TO ROLE IDENTIFIER($SCOPEIQ_READ_ROLE);
-- Application role: read RAW/REF, read-write CORE/WF, insert-only AUDIT
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT SELECT ON FUTURE TABLES IN SCHEMA REF TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA CORE TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA WF   TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA APP TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RAW TO ROLE IDENTIFIER($SCOPEIQ_APP_ROLE);

-- Logging level for the procedures (event table must be set on the account; see 12_logging_and_monitoring.sql)
EXECUTE IMMEDIATE 'ALTER DATABASE ' || $SCOPEIQ_DB || ' SET LOG_LEVEL = ' || $SCOPEIQ_LOG_LEVEL || ' TRACE_LEVEL = ' || $SCOPEIQ_TRACE_LEVEL;
