-- =====================================================================================================
-- 03  Tables for every layer (RAW, REF, CORE, WF, AUDIT). Idempotent (IF NOT EXISTS).
-- GENERATED by backend/scripts/generate_snowflake_sql.py from scopeiq/db/schema.py - do not edit by hand.
-- =====================================================================================================
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
USE WAREHOUSE IDENTIFIER($SCOPEIQ_WH);

-- ---------------------------------------------------------------- RAW
CREATE TABLE IF NOT EXISTS RAW.ST_SITE (
    ID                       VARCHAR NOT NULL,
    NAME                     VARCHAR,
    SITE_NAME__C             VARCHAR,
    MARKET__C                VARCHAR,
    CUSTOMER__C              VARCHAR,
    STREET__C                VARCHAR,
    CITY__C                  VARCHAR,
    STATE__C                 VARCHAR,
    ZIP__C                   VARCHAR,
    LATITUDE__C              NUMBER(18,4),
    LONGITUDE__C             NUMBER(18,4),
    STRUCTURE_TYPE__C        VARCHAR,
    STRUCTURE_HEIGHT_FT__C   NUMBER(18,4),
    STRUCTURE_OWNER__C       VARCHAR,
    SITE_STATUS__C           VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    CONSTRAINT PK_ST_SITE PRIMARY KEY (ID)
) COMMENT = 'SiteTracker Site export';

CREATE TABLE IF NOT EXISTS RAW.ST_PROJECT (
    ID                       VARCHAR NOT NULL,
    NAME                     VARCHAR,
    SITE__C                  VARCHAR,
    PROJECT_TYPE__C          VARCHAR,
    SCOPING_SERVICE_LINE__C  VARCHAR,
    SCOPING_ASSIGNED_DATE__C VARCHAR,
    BOM_STATUS__C            VARCHAR,
    CURRENT_BOM_REV__C       VARCHAR,
    CX_SERVICE_PROVIDER__C   VARCHAR,
    SCOPING_COMPLETE_FORECAST__C VARCHAR,
    SCOPING_COMPLETE_ACTUAL__C VARCHAR,
    FBA_DATE__C              VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    CONSTRAINT PK_ST_PROJECT PRIMARY KEY (ID)
) COMMENT = 'SiteTracker Project export';

CREATE TABLE IF NOT EXISTS RAW.ST_MILESTONE (
    ID                       VARCHAR NOT NULL,
    PROJECT__C               VARCHAR,
    NAME                     VARCHAR,
    FORECAST_DATE__C         VARCHAR,
    ACTUAL_DATE__C           VARCHAR,
    STATUS__C                VARCHAR,
    SEQUENCE__C              NUMBER(18,4),
    LOADED_AT                TIMESTAMP_TZ,
    CONSTRAINT PK_ST_MILESTONE PRIMARY KEY (ID)
) COMMENT = 'SiteTracker Milestone export';

CREATE TABLE IF NOT EXISTS RAW.ST_DOCUMENT (
    ID                       VARCHAR NOT NULL,
    PROJECT__C               VARCHAR,
    DOCUMENT_TYPE__C         VARCHAR,
    TITLE                    VARCHAR,
    FILE_PATH__C             VARCHAR,
    FILE_FORMAT__C           VARCHAR,
    REVISION__C              VARCHAR,
    UPLOADED_DATE__C         VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    CONSTRAINT PK_ST_DOCUMENT PRIMARY KEY (ID)
) COMMENT = 'SiteTracker Document export';

-- ---------------------------------------------------------------- REF
CREATE TABLE IF NOT EXISTS REF.MATERIAL_CATALOG (
    CATALOG_KEY              VARCHAR NOT NULL,
    CATEGORY                 VARCHAR,
    SUBCATEGORY              VARCHAR,
    MANUFACTURER             VARCHAR,
    MODEL                    VARCHAR,
    MANUFACTURER_PN          VARCHAR,
    CUSTOMER_PN              VARCHAR,
    DESCRIPTION              VARCHAR,
    UOM                      VARCHAR,
    SUPPLY                   VARCHAR,
    CUSTOMER_APPROVED        VARCHAR,
    UNIT_COST_USD            NUMBER(18,4),
    RF_PORTS                 NUMBER(18,4),
    POWER_W                  NUMBER(18,4),
    BANDS                    VARCHAR,
    TECHNOLOGY               VARCHAR,
    HEIGHT_M                 NUMBER(18,4),
    WIDTH_M                  NUMBER(18,4),
    DEPTH_M                  NUMBER(18,4),
    ALIASES                  VARCHAR,
    VERSION                  NUMBER(18,4),
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_MATERIAL_CATALOG PRIMARY KEY (CATALOG_KEY)
) COMMENT = 'Reference data from material_catalog.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.KIT_RULE (
    RULE_ID                  VARCHAR NOT NULL,
    TRIGGER_CODE             VARCHAR,
    TRIGGER_TEXT             VARCHAR,
    CHILD_KEY                VARCHAR,
    QTY_EXPR                 VARCHAR,
    SPARE_EXPR               VARCHAR,
    SCOPE                    VARCHAR,
    SOURCE_TEMPLATE          VARCHAR,
    NOTES                    VARCHAR,
    CARRIER                  VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_KIT_RULE PRIMARY KEY (RULE_ID, VERSION)
) COMMENT = 'Reference data from kit_rules.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.TRUNK_STEP (
    STEP_FT                  NUMBER(18,4) NOT NULL,
    CATALOG_KEY              VARCHAR,
    RULE_TEXT                VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_TRUNK_STEP PRIMARY KEY (STEP_FT, VERSION)
) COMMENT = 'Reference data from trunk_steps.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.CONSISTENCY_RULE (
    RULE_ID                  VARCHAR NOT NULL,
    FAMILY                   VARCHAR,
    NAME                     VARCHAR,
    DESCRIPTION              VARCHAR,
    SEVERITY                 VARCHAR,
    OUTCOME                  VARCHAR,
    TARGET_DOC               VARCHAR,
    PARAMS_JSON              VARCHAR,
    STREAMS                  VARCHAR,
    CARRIER                  VARCHAR,
    ACTIVE                   VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_CONSISTENCY_RULE PRIMARY KEY (RULE_ID, VERSION)
) COMMENT = 'Reference data from consistency_rules.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.SERVICE_DRIVER_MATRIX (
    DRIVER_CODE              VARCHAR NOT NULL,
    DESCRIPTION              VARCHAR,
    DELTA_ACTION             VARCHAR,
    EQUIPMENT_CLASS          VARCHAR,
    UOM                      VARCHAR,
    QTY_BASIS                VARCHAR,
    NOTES                    VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_SERVICE_DRIVER_MATRIX PRIMARY KEY (DRIVER_CODE, VERSION)
) COMMENT = 'Reference data from service_driver_matrix.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.RATE_CARD (
    MARKET                   VARCHAR NOT NULL,
    SERVICE_PROVIDER         VARCHAR NOT NULL,
    DRIVER_CODE              VARCHAR NOT NULL,
    UNIT_RATE_USD            NUMBER(18,4),
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    NOTES                    VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_RATE_CARD PRIMARY KEY (MARKET, SERVICE_PROVIDER, DRIVER_CODE, VERSION)
) COMMENT = 'Reference data from rate_card.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.SITE_REQUIREMENT_RULE (
    RULE_ID                  VARCHAR NOT NULL,
    PRIORITY                 NUMBER(18,4),
    STRUCTURE_TYPE           VARCHAR,
    MIN_HEIGHT_FT            NUMBER(18,4),
    MAX_HEIGHT_FT            NUMBER(18,4),
    MIN_NEW_LOAD_LB          NUMBER(18,4),
    REQUIRES_AAU             VARCHAR,
    ACCESS_METHOD            VARCHAR,
    CRANE_DAYS               NUMBER(18,4),
    MANLIFT_DAYS             NUMBER(18,4),
    RIGGING_CLASS            VARCHAR,
    EHS_ALERT                VARCHAR,
    DESCRIPTION              VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_SITE_REQUIREMENT_RULE PRIMARY KEY (RULE_ID, VERSION)
) COMMENT = 'Reference data from site_requirement_rules.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.CYCLE_TIME_PARAM (
    PARAM                    VARCHAR NOT NULL,
    VALUE                    NUMBER(18,4),
    UOM                      VARCHAR,
    DESCRIPTION              VARCHAR,
    VERSION                  NUMBER(18,4) NOT NULL,
    EFFECTIVE_FROM           DATE,
    EFFECTIVE_TO             DATE,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_CYCLE_TIME_PARAM PRIMARY KEY (PARAM, VERSION)
) COMMENT = 'Reference data from cycle_time_params.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.REASON_CODE (
    REASON_CODE              VARCHAR NOT NULL,
    CATEGORY                 VARCHAR,
    DESCRIPTION              VARCHAR,
    FAULT_PARTY              VARCHAR,
    APPLIES_TO               VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_REASON_CODE PRIMARY KEY (REASON_CODE)
) COMMENT = 'Reference data from reason_codes.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.PERSONA (
    ROLE_CODE                VARCHAR NOT NULL,
    PERSONA_NAME             VARCHAR,
    ORGANISATION             VARCHAR,
    GOALS                    VARCHAR,
    KEY_SCREENS              VARCHAR,
    SNOWFLAKE_ROLE           VARCHAR,
    CAN_APPROVE              VARCHAR,
    DATA_SCOPE               VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_PERSONA PRIMARY KEY (ROLE_CODE)
) COMMENT = 'Reference data from personas.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.APP_USER (
    USER_ID                  VARCHAR NOT NULL,
    DISPLAY_NAME             VARCHAR,
    EMAIL                    VARCHAR,
    ROLE_CODE                VARCHAR,
    ORGANISATION             VARCHAR,
    MARKET                   VARCHAR,
    SERVICE_PROVIDER         VARCHAR,
    ACTIVE                   VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_APP_USER PRIMARY KEY (USER_ID)
) COMMENT = 'Reference data from users.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.WORKFLOW_STATE (
    ENTITY_TYPE              VARCHAR NOT NULL,
    STATE                    VARCHAR NOT NULL,
    SEQ                      NUMBER(18,4),
    IS_INITIAL               VARCHAR,
    IS_TERMINAL              VARCHAR,
    IS_LOCKED                VARCHAR,
    OWNER_ROLE               VARCHAR,
    DESCRIPTION              VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_WORKFLOW_STATE PRIMARY KEY (ENTITY_TYPE, STATE)
) COMMENT = 'Reference data from workflow_states.csv (versioned, effective-dated)';

CREATE TABLE IF NOT EXISTS REF.WORKFLOW_TRANSITION (
    ENTITY_TYPE              VARCHAR NOT NULL,
    FROM_STATE               VARCHAR NOT NULL,
    ACTION                   VARCHAR NOT NULL,
    TO_STATE                 VARCHAR,
    ALLOWED_ROLES            VARCHAR,
    REQUIRES_REASON          VARCHAR,
    REQUIRES_COMMENT         VARCHAR,
    NOTIFY_ROLES             VARCHAR,
    DESCRIPTION              VARCHAR,
    LOADED_AT                TIMESTAMP_TZ,
    LOADED_BY                VARCHAR,
    CONSTRAINT PK_WORKFLOW_TRANSITION PRIMARY KEY (ENTITY_TYPE, FROM_STATE, ACTION)
) COMMENT = 'Reference data from workflow_transitions.csv (versioned, effective-dated)';

-- ---------------------------------------------------------------- CORE
CREATE TABLE IF NOT EXISTS CORE.SITE (
    SITE_ID                  VARCHAR NOT NULL,
    SF_ID                    VARCHAR,
    SITE_NAME                VARCHAR,
    MARKET                   VARCHAR,
    CUSTOMER                 VARCHAR,
    ADDRESS                  VARCHAR,
    CITY                     VARCHAR,
    STATE                    VARCHAR,
    ZIP                      VARCHAR,
    LATITUDE                 NUMBER(18,4),
    LONGITUDE                NUMBER(18,4),
    STRUCTURE_TYPE           VARCHAR,
    HEIGHT_FT                NUMBER(18,4),
    STRUCTURE_OWNER          VARCHAR,
    SITE_STATUS              VARCHAR,
    STREAM                   VARCHAR,
    PROJECT_SF_ID            VARCHAR,
    PROJECT_NAME             VARCHAR,
    PROJECT_TYPE             VARCHAR,
    SERVICE_LINE             VARCHAR,
    CX_SP                    VARCHAR,
    ASSIGNED_DATE            VARCHAR,
    SCOPING_FORECAST         VARCHAR,
    SCOPING_ACTUAL           VARCHAR,
    FBA_DATE                 VARCHAR,
    CURRENT_BOM_REV          VARCHAR,
    WORKFLOW_STATE           VARCHAR,
    ASSIGNED_TO              VARCHAR,
    LAST_RUN_ID              VARCHAR,
    UPDATED_AT               TIMESTAMP_TZ,
    UPDATED_BY               VARCHAR,
    CONSTRAINT PK_SITE PRIMARY KEY (SITE_ID)
) COMMENT = 'One row per site (SiteTracker + RFDS site info + workflow state)';

CREATE TABLE IF NOT EXISTS CORE.MILESTONE (
    MILESTONE_SF_ID          VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    NAME                     VARCHAR,
    SEQ                      NUMBER(38,0),
    FORECAST                 VARCHAR,
    ACTUAL                   VARCHAR,
    STATUS                   VARCHAR,
    CONSTRAINT PK_MILESTONE PRIMARY KEY (MILESTONE_SF_ID)
) COMMENT = 'SiteTracker milestones';

CREATE TABLE IF NOT EXISTS CORE.DOCUMENT (
    DOC_ID                   VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    DOC_TYPE                 VARCHAR,
    FILE_NAME                VARCHAR,
    REL_PATH                 VARCHAR,
    FILE_FORMAT              VARCHAR,
    REVISION                 VARCHAR,
    REVISION_RANK            NUMBER(38,0),
    FILE_HASH                VARCHAR,
    SIZE_BYTES               NUMBER(38,0),
    DOC_DATE                 VARCHAR,
    SOURCE                   VARCHAR,
    STATUS                   VARCHAR,
    REGISTERED_AT            TIMESTAMP_TZ,
    REGISTERED_BY            VARCHAR,
    CONSTRAINT PK_DOCUMENT PRIMARY KEY (DOC_ID)
) COMMENT = 'Document registry (latest revision = CURRENT)';

CREATE TABLE IF NOT EXISTS CORE.UPLOAD (
    UPLOAD_ID                VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    DOC_TYPE                 VARCHAR,
    FILE_NAME                VARCHAR,
    STAGE_PATH               VARCHAR,
    SIZE_BYTES               NUMBER(38,0),
    FILE_HASH                VARCHAR,
    UPLOADED_BY              VARCHAR,
    UPLOADED_AT              TIMESTAMP_TZ,
    STATUS                   VARCHAR,
    DOC_ID                   VARCHAR,
    MESSAGE                  VARCHAR,
    CONSTRAINT PK_UPLOAD PRIMARY KEY (UPLOAD_ID)
) COMMENT = 'Artifacts uploaded through the app before registration';

CREATE TABLE IF NOT EXISTS CORE.PIPELINE_RUN (
    RUN_ID                   VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    STARTED_AT               TIMESTAMP_TZ,
    FINISHED_AT              TIMESTAMP_TZ,
    STATUS                   VARCHAR,
    TRIGGERED_BY             VARCHAR,
    CORRELATION_ID           VARCHAR,
    STEPS                    VARIANT,
    SUMMARY                  VARIANT,
    WARNINGS                 VARIANT,
    REFERENCE_VERSIONS       VARIANT,
    CONSTRAINT PK_PIPELINE_RUN PRIMARY KEY (RUN_ID)
) COMMENT = 'One row per pipeline execution for a site';

CREATE TABLE IF NOT EXISTS CORE.EXTRACTED_FIELD (
    FIELD_ID                 VARCHAR NOT NULL,
    RUN_ID                   VARCHAR,
    SITE_ID                  VARCHAR NOT NULL,
    DOC_ID                   VARCHAR,
    PAGE                     VARCHAR,
    FIELD_NAME               VARCHAR,
    VALUE                    VARIANT,
    CONFIDENCE               NUMBER(18,4),
    METHOD                   VARCHAR,
    NEEDS_REVIEW             BOOLEAN,
    REVIEWED_BY              VARCHAR,
    REVIEWED_AT              TIMESTAMP_TZ,
    CONSTRAINT PK_EXTRACTED_FIELD PRIMARY KEY (FIELD_ID)
) COMMENT = 'Every value read from a document, with confidence';

CREATE TABLE IF NOT EXISTS CORE.CONFIG_LINE (
    LINE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR,
    SITE_ID                  VARCHAR NOT NULL,
    SOURCE                   VARCHAR,
    SECTOR                   VARCHAR,
    POSITION                 NUMBER(38,0),
    KIND                     VARCHAR,
    CATALOG_KEY              VARCHAR,
    MODEL_TEXT               VARCHAR,
    STATUS                   VARCHAR,
    RAD_CENTER_FT            NUMBER(18,4),
    AZIMUTH_DEG              NUMBER(18,4),
    MECH_TILT                NUMBER(18,4),
    BANDS                    VARCHAR,
    SOURCE_REF               VARCHAR,
    CONFIDENCE               NUMBER(18,4),
    ATTRS                    VARIANT,
    CONSTRAINT PK_CONFIG_LINE PRIMARY KEY (LINE_ID)
) COMMENT = 'Equipment per source (RFDS/CD/FIELD/MA)';

CREATE TABLE IF NOT EXISTS CORE.SECTOR_INFO (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    SECTOR                   VARCHAR NOT NULL,
    AZ_RFDS                  NUMBER(18,4),
    AZ_CD                    NUMBER(18,4),
    AZ_FIELD                 NUMBER(18,4),
    NEW_FRAME                BOOLEAN,
    SLED_CD                  BOOLEAN,
    SLED_FIELD               BOOLEAN,
    CONSTRAINT PK_SECTOR_INFO PRIMARY KEY (SITE_ID, RUN_ID, SECTOR)
) COMMENT = 'Sector azimuths and mounts per source';

CREATE TABLE IF NOT EXISTS CORE.TRUNK_MEASURE (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    SOURCE                   VARCHAR NOT NULL,
    TRUNK_COUNT              NUMBER(38,0),
    VERTICAL_FT              NUMBER(18,4),
    HORIZONTAL_FT            NUMBER(18,4),
    REQUIRED_FT              NUMBER(18,4),
    SPECIFIED_FT             NUMBER(18,4),
    SOURCE_REF               VARCHAR,
    CONSTRAINT PK_TRUNK_MEASURE PRIMARY KEY (SITE_ID, RUN_ID, SOURCE)
) COMMENT = 'Cable schedule (CD) and measured route (FIELD)';

CREATE TABLE IF NOT EXISTS CORE.ANALYSIS_RESULT (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    KIND                     VARCHAR NOT NULL,
    REPORT_ID                VARCHAR,
    REPORT_DATE              VARCHAR,
    RESULT                   VARCHAR,
    CAPACITY_PCT             NUMBER(18,4),
    CAPACITY_AFTER_PCT       NUMBER(18,4),
    RFDS_REVISION            VARCHAR,
    MODIFICATIONS            VARIANT,
    SOURCE_REF               VARCHAR,
    CONSTRAINT PK_ANALYSIS_RESULT PRIMARY KEY (SITE_ID, RUN_ID, KIND)
) COMMENT = 'Mount (MA) and structural (SA) analysis results';

CREATE TABLE IF NOT EXISTS CORE.REV0_LINE (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    ROW_NUM                  NUMBER(38,0) NOT NULL,
    SECTOR                   VARCHAR,
    CATALOG_KEY              VARCHAR,
    MODEL                    VARCHAR,
    MFR_PN                   VARCHAR,
    CUSTOMER_PN              VARCHAR,
    DESIGN_QTY               NUMBER(18,4),
    SPARE_QTY                NUMBER(18,4),
    ACTION                   VARCHAR,
    RULE_ID                  VARCHAR,
    SOURCE                   VARCHAR,
    CONSTRAINT PK_REV0_LINE PRIMARY KEY (SITE_ID, RUN_ID, ROW_NUM)
) COMMENT = 'REV 0 preliminary BOM rows as read';

CREATE TABLE IF NOT EXISTS CORE.FIELD_OBJECT (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    OBJECT_ID                VARCHAR NOT NULL,
    OBJECT_TYPE              VARCHAR,
    SECTOR                   VARCHAR,
    POSITION                 NUMBER(38,0),
    BEARING_DEG              NUMBER(18,4),
    FACING_AZ_DEG            NUMBER(18,4),
    CENTER_HEIGHT_FT         NUMBER(18,4),
    DIMS_IN                  VARIANT,
    MODEL_GUESS              VARCHAR,
    CONFIDENCE               NUMBER(18,4),
    ROUTE_LENGTH_FT          NUMBER(18,4),
    METHOD                   VARCHAR,
    CONSTRAINT PK_FIELD_OBJECT PRIMARY KEY (SITE_ID, RUN_ID, OBJECT_ID)
) COMMENT = 'Drone survey objects (vendor CSV or point cloud)';

CREATE TABLE IF NOT EXISTS CORE.EVIDENCE_FRAME (
    FRAME_ID                 VARCHAR NOT NULL,
    RUN_ID                   VARCHAR,
    SITE_ID                  VARCHAR NOT NULL,
    FRAME_INDEX              NUMBER(38,0),
    TIME_S                   NUMBER(18,4),
    BEARING_DEG              NUMBER(18,4),
    SECTOR                   VARCHAR,
    SHARPNESS                NUMBER(18,4),
    PATH                     VARCHAR,
    SELECTED                 BOOLEAN,
    CONSTRAINT PK_EVIDENCE_FRAME PRIMARY KEY (FRAME_ID)
) COMMENT = 'Frames sampled from the drone orbit video';

CREATE TABLE IF NOT EXISTS CORE.DISCREPANCY (
    DISC_ID                  VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR,
    RULE_ID                  VARCHAR,
    FAMILY                   VARCHAR,
    SEVERITY                 VARCHAR,
    OUTCOME                  VARCHAR,
    TITLE                    VARCHAR,
    DESCRIPTION              VARCHAR,
    SECTOR                   VARCHAR,
    POSITION                 NUMBER(38,0),
    EXPECTED                 VARIANT,
    FOUND                    VARIANT,
    GOVERNING                VARCHAR,
    SOURCES                  VARIANT,
    TARGET_DOC               VARCHAR,
    TARGET_SHEET             VARCHAR,
    BOM_IMPACT               VARCHAR,
    EVIDENCE                 VARIANT,
    CONFIDENCE               NUMBER(18,4),
    STATUS                   VARCHAR,
    REASON_CODE              VARCHAR,
    ASSIGNED_TO              VARCHAR,
    FIRST_SEEN_RUN           VARCHAR,
    LAST_SEEN_RUN            VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    UPDATED_AT               TIMESTAMP_TZ,
    UPDATED_BY               VARCHAR,
    CONSTRAINT PK_DISCREPANCY PRIMARY KEY (DISC_ID)
) COMMENT = 'Findings; id is stable across runs so human decisions survive re-runs';

CREATE TABLE IF NOT EXISTS CORE.EQUIPMENT_DELTA (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    SEQ                      NUMBER(38,0) NOT NULL,
    SECTOR                   VARCHAR,
    POSITION                 NUMBER(38,0),
    KIND                     VARCHAR,
    CATALOG_KEY              VARCHAR,
    ACTION                   VARCHAR,
    FROM_POSITION            NUMBER(38,0),
    RAD_CENTER_FT            NUMBER(18,4),
    BASIS                    VARCHAR,
    SOURCE_REF               VARCHAR,
    CONSTRAINT PK_EQUIPMENT_DELTA PRIMARY KEY (SITE_ID, RUN_ID, SEQ)
) COMMENT = 'NEW / EXISTING / REMOVED / RELOCATED / REUSED per device';

CREATE TABLE IF NOT EXISTS CORE.BOM_REVISION (
    BOM_REV_ID               VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    REV_NO                   NUMBER(38,0),
    REV_LABEL                VARCHAR,
    KIND                     VARCHAR,
    STATUS                   VARCHAR,
    LOCKED                   BOOLEAN,
    RUN_ID                   VARCHAR,
    PARENT_REV_ID            VARCHAR,
    REASON_CODE              VARCHAR,
    TRUNK_PLAN               VARIANT,
    TOTALS                   VARIANT,
    CREATED_AT               TIMESTAMP_TZ,
    CREATED_BY               VARCHAR,
    APPROVED_AT              TIMESTAMP_TZ,
    APPROVED_BY              VARCHAR,
    NOTES                    VARCHAR,
    CONSTRAINT PK_BOM_REVISION PRIMARY KEY (BOM_REV_ID)
) COMMENT = 'BOM revisions: REV 0 (tool), REV 1..n (generated/edited); FBA revisions are locked';

CREATE TABLE IF NOT EXISTS CORE.BOM_LINE (
    LINE_ID                  VARCHAR NOT NULL,
    BOM_REV_ID               VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    SECTOR                   VARCHAR,
    CATALOG_KEY              VARCHAR,
    DESIGN_QTY               NUMBER(18,4),
    SPARE_QTY                NUMBER(18,4),
    TOTAL_QTY                NUMBER(18,4),
    ACTION                   VARCHAR,
    RULE_ID                  VARCHAR,
    SOURCE                   VARCHAR,
    PARENT_KEY               VARCHAR,
    REASON_CODE              VARCHAR,
    TRACE                    VARIANT,
    EDITED_BY                VARCHAR,
    EDITED_AT                TIMESTAMP_TZ,
    CONSTRAINT PK_BOM_LINE PRIMARY KEY (LINE_ID)
) COMMENT = 'BOM lines with rule ID and source reference';

CREATE TABLE IF NOT EXISTS CORE.BOM_CHANGE (
    CHANGE_ID                VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    FROM_REV_ID              VARCHAR,
    TO_REV_ID                VARCHAR,
    SECTOR                   VARCHAR,
    CATALOG_KEY              VARCHAR,
    ACTION                   VARCHAR,
    FROM_QTY                 NUMBER(18,4),
    TO_QTY                   NUMBER(18,4),
    DELTA                    NUMBER(18,4),
    REASONS                  VARIANT,
    CONSTRAINT PK_BOM_CHANGE PRIMARY KEY (CHANGE_ID)
) COMMENT = 'Line-level differences between two revisions with reasons';

CREATE TABLE IF NOT EXISTS CORE.DRIVER_LINE (
    LINE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR,
    SITE_ID                  VARCHAR NOT NULL,
    DRIVER_CODE              VARCHAR,
    DESCRIPTION              VARCHAR,
    SECTOR                   VARCHAR,
    QTY                      NUMBER(18,4),
    UOM                      VARCHAR,
    UNIT_RATE                NUMBER(18,4),
    AMOUNT                   NUMBER(18,4),
    BASIS                    VARCHAR,
    CONSTRAINT PK_DRIVER_LINE PRIMARY KEY (LINE_ID)
) COMMENT = 'Service drivers (FPP codes) with illustrative rates';

CREATE TABLE IF NOT EXISTS CORE.SITE_REQUIREMENT (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    RULE_ID                  VARCHAR,
    ACCESS_METHOD            VARCHAR,
    CRANE_DAYS               NUMBER(18,4),
    MANLIFT_DAYS             NUMBER(18,4),
    RIGGING_CLASS            VARCHAR,
    HOLD                     BOOLEAN,
    INPUTS                   VARIANT,
    CONSTRAINT PK_SITE_REQUIREMENT PRIMARY KEY (SITE_ID, RUN_ID)
) COMMENT = 'Access, rigging and hold requirements';

CREATE TABLE IF NOT EXISTS CORE.ESTIMATE (
    SITE_ID                  VARCHAR NOT NULL,
    RUN_ID                   VARCHAR NOT NULL,
    CYCLE_DAYS               NUMBER(18,4),
    SERVICES_USD             NUMBER(18,4),
    MATERIAL_USD             NUMBER(18,4),
    TOTAL_USD                NUMBER(18,4),
    DETAIL                   VARIANT,
    CONSTRAINT PK_ESTIMATE PRIMARY KEY (SITE_ID, RUN_ID)
) COMMENT = 'Cost and cycle-time estimate';

CREATE TABLE IF NOT EXISTS CORE.EHS_ALERT (
    ALERT_ID                 VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    RULE_ID                  VARCHAR,
    SEVERITY                 VARCHAR,
    ALERT_TEXT               VARCHAR,
    STATUS                   VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    UPDATED_AT               TIMESTAMP_TZ,
    UPDATED_BY               VARCHAR,
    CONSTRAINT PK_EHS_ALERT PRIMARY KEY (ALERT_ID)
) COMMENT = 'EH&S alerts (rooftop crane, guyed tower, SA fail)';

CREATE TABLE IF NOT EXISTS CORE.REDLINE (
    REDLINE_ID               VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    DISC_ID                  VARCHAR,
    DOC_TYPE                 VARCHAR,
    DOC_REVISION             VARCHAR,
    SHEET                    VARCHAR,
    MARKUP                   VARCHAR,
    CHANGE_FROM              VARCHAR,
    CHANGE_TO                VARCHAR,
    STATUS                   VARCHAR,
    PDF_PATH                 VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    UPDATED_AT               TIMESTAMP_TZ,
    UPDATED_BY               VARCHAR,
    CONSTRAINT PK_REDLINE PRIMARY KEY (REDLINE_ID)
) COMMENT = 'Redlines to apply to CD / MA documents';

CREATE TABLE IF NOT EXISTS CORE.RFI (
    RFI_ID                   VARCHAR NOT NULL,
    SITE_ID                  VARCHAR NOT NULL,
    TO_PARTY                 VARCHAR,
    SUBJECT                  VARCHAR,
    QUESTION                 VARCHAR,
    PROPOSED_ANSWER          VARCHAR,
    ANSWER                   VARCHAR,
    DISC_IDS                 VARIANT,
    STATUS                   VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    UPDATED_AT               TIMESTAMP_TZ,
    UPDATED_BY               VARCHAR,
    CONSTRAINT PK_RFI PRIMARY KEY (RFI_ID)
) COMMENT = 'Requests for information';

-- ---------------------------------------------------------------- WF
CREATE TABLE IF NOT EXISTS WF.WORKFLOW_EVENT (
    EVENT_ID                 VARCHAR NOT NULL,
    ENTITY_TYPE              VARCHAR NOT NULL,
    ENTITY_ID                VARCHAR NOT NULL,
    SITE_ID                  VARCHAR,
    FROM_STATE               VARCHAR,
    ACTION                   VARCHAR,
    TO_STATE                 VARCHAR,
    ACTOR_USER_ID            VARCHAR,
    ACTOR_ROLE               VARCHAR,
    REASON_CODE              VARCHAR,
    COMMENT                  VARCHAR,
    EVENT_TS                 TIMESTAMP_TZ,
    CORRELATION_ID           VARCHAR,
    CONSTRAINT PK_WORKFLOW_EVENT PRIMARY KEY (EVENT_ID)
) COMMENT = 'Every workflow transition (status history)';

CREATE TABLE IF NOT EXISTS WF.NOTIFICATION (
    NOTIFICATION_ID          VARCHAR NOT NULL,
    ROLE_CODE                VARCHAR,
    USER_ID                  VARCHAR,
    SITE_ID                  VARCHAR,
    ENTITY_TYPE              VARCHAR,
    ENTITY_ID                VARCHAR,
    MESSAGE                  VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    READ_AT                  TIMESTAMP_TZ,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID)
) COMMENT = 'Role inbox items created by transitions';

CREATE TABLE IF NOT EXISTS WF.COMMENT (
    COMMENT_ID               VARCHAR NOT NULL,
    ENTITY_TYPE              VARCHAR,
    ENTITY_ID                VARCHAR,
    SITE_ID                  VARCHAR,
    USER_ID                  VARCHAR,
    COMMENT_TEXT             VARCHAR,
    CREATED_AT               TIMESTAMP_TZ,
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENT_ID)
) COMMENT = 'Free-text comments';

-- ---------------------------------------------------------------- AUDIT
CREATE TABLE IF NOT EXISTS AUDIT.AUDIT_LOG (
    AUDIT_ID                 VARCHAR NOT NULL,
    EVENT_TS                 TIMESTAMP_TZ,
    ENTITY_TYPE              VARCHAR,
    ENTITY_ID                VARCHAR,
    SITE_ID                  VARCHAR,
    ACTION                   VARCHAR,
    ACTOR_USER_ID            VARCHAR,
    ACTOR_ROLE               VARCHAR,
    REASON_CODE              VARCHAR,
    COMMENT                  VARCHAR,
    BEFORE_VALUE             VARIANT,
    AFTER_VALUE              VARIANT,
    CORRELATION_ID           VARCHAR,
    SOURCE                   VARCHAR,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
) COMMENT = 'Who changed what, when and why (immutable)';

CREATE TABLE IF NOT EXISTS AUDIT.APP_LOG (
    LOG_ID                   VARCHAR NOT NULL,
    LOG_TS                   TIMESTAMP_TZ,
    LEVEL                    VARCHAR,
    LOGGER                   VARCHAR,
    MESSAGE                  VARCHAR,
    CORRELATION_ID           VARCHAR,
    USER_ID                  VARCHAR,
    SITE_ID                  VARCHAR,
    COMPONENT                VARCHAR,
    DETAIL                   VARIANT,
    CONSTRAINT PK_APP_LOG PRIMARY KEY (LOG_ID)
) COMMENT = 'Application log sink (level set per environment)';

CREATE TABLE IF NOT EXISTS AUDIT.ERROR_LOG (
    ERROR_ID                 VARCHAR NOT NULL,
    ERROR_TS                 TIMESTAMP_TZ,
    ERROR_CODE               VARCHAR,
    MESSAGE                  VARCHAR,
    EXCEPTION_TYPE           VARCHAR,
    STACK                    VARCHAR,
    WHERE_RAISED             VARCHAR,
    CORRELATION_ID           VARCHAR,
    USER_ID                  VARCHAR,
    SITE_ID                  VARCHAR,
    COMPONENT                VARCHAR,
    DETAILS                  VARIANT,
    CONSTRAINT PK_ERROR_LOG PRIMARY KEY (ERROR_ID)
) COMMENT = 'Errors with stack and context';

