-- =====================================================================================================
-- 06  Seed CORE.SITE and CORE.MILESTONE from the SiteTracker landing tables so sites appear in the app
--     (state ASSIGNED) before their first pipeline run. The pipeline refreshes the same rows on every run.
-- =====================================================================================================
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
USE WAREHOUSE IDENTIFIER($SCOPEIQ_WH);

MERGE INTO CORE.SITE t
USING (
  SELECT s.NAME AS SITE_ID, s.ID AS SF_ID, s.SITE_NAME__C AS SITE_NAME, s.MARKET__C AS MARKET, s.CUSTOMER__C AS CUSTOMER,
         s.STREET__C AS ADDRESS, s.CITY__C AS CITY, s.STATE__C AS STATE, s.ZIP__C AS ZIP, s.LATITUDE__C AS LATITUDE,
         s.LONGITUDE__C AS LONGITUDE, s.STRUCTURE_TYPE__C AS STRUCTURE_TYPE, s.STRUCTURE_HEIGHT_FT__C AS HEIGHT_FT,
         s.STRUCTURE_OWNER__C AS STRUCTURE_OWNER, s.SITE_STATUS__C AS SITE_STATUS,
         CASE p.SCOPING_SERVICE_LINE__C WHEN 'Site Design Scoping' THEN 'DESIGN' WHEN 'Network Deployment Scoping' THEN 'DEPLOYMENT' ELSE 'BOM' END AS STREAM,
         p.ID AS PROJECT_SF_ID, p.NAME AS PROJECT_NAME, p.PROJECT_TYPE__C AS PROJECT_TYPE, p.SCOPING_SERVICE_LINE__C AS SERVICE_LINE,
         p.CX_SERVICE_PROVIDER__C AS CX_SP, p.SCOPING_ASSIGNED_DATE__C AS ASSIGNED_DATE, p.SCOPING_COMPLETE_FORECAST__C AS SCOPING_FORECAST,
         p.SCOPING_COMPLETE_ACTUAL__C AS SCOPING_ACTUAL, p.FBA_DATE__C AS FBA_DATE, p.CURRENT_BOM_REV__C AS CURRENT_BOM_REV
  FROM RAW.ST_SITE s
  LEFT JOIN RAW.ST_PROJECT p ON p.SITE__C = s.ID
  QUALIFY ROW_NUMBER() OVER (PARTITION BY s.NAME ORDER BY p.SCOPING_ASSIGNED_DATE__C DESC NULLS LAST) = 1
) s ON t.SITE_ID = s.SITE_ID
WHEN MATCHED THEN UPDATE SET
  SF_ID = s.SF_ID, SITE_NAME = s.SITE_NAME, MARKET = s.MARKET, CUSTOMER = s.CUSTOMER, ADDRESS = s.ADDRESS, CITY = s.CITY, STATE = s.STATE,
  ZIP = s.ZIP, LATITUDE = s.LATITUDE, LONGITUDE = s.LONGITUDE, STRUCTURE_TYPE = s.STRUCTURE_TYPE, HEIGHT_FT = s.HEIGHT_FT,
  STRUCTURE_OWNER = s.STRUCTURE_OWNER, SITE_STATUS = s.SITE_STATUS, STREAM = s.STREAM, PROJECT_SF_ID = s.PROJECT_SF_ID,
  PROJECT_NAME = s.PROJECT_NAME, PROJECT_TYPE = s.PROJECT_TYPE, SERVICE_LINE = s.SERVICE_LINE, CX_SP = s.CX_SP,
  ASSIGNED_DATE = s.ASSIGNED_DATE, SCOPING_FORECAST = s.SCOPING_FORECAST, SCOPING_ACTUAL = s.SCOPING_ACTUAL, FBA_DATE = s.FBA_DATE,
  CURRENT_BOM_REV = s.CURRENT_BOM_REV, UPDATED_AT = CURRENT_TIMESTAMP(), UPDATED_BY = 'sitetracker-sync'
WHEN NOT MATCHED THEN INSERT (SITE_ID, SF_ID, SITE_NAME, MARKET, CUSTOMER, ADDRESS, CITY, STATE, ZIP, LATITUDE, LONGITUDE, STRUCTURE_TYPE,
  HEIGHT_FT, STRUCTURE_OWNER, SITE_STATUS, STREAM, PROJECT_SF_ID, PROJECT_NAME, PROJECT_TYPE, SERVICE_LINE, CX_SP, ASSIGNED_DATE,
  SCOPING_FORECAST, SCOPING_ACTUAL, FBA_DATE, CURRENT_BOM_REV, WORKFLOW_STATE, UPDATED_AT, UPDATED_BY)
VALUES (s.SITE_ID, s.SF_ID, s.SITE_NAME, s.MARKET, s.CUSTOMER, s.ADDRESS, s.CITY, s.STATE, s.ZIP, s.LATITUDE, s.LONGITUDE, s.STRUCTURE_TYPE,
  s.HEIGHT_FT, s.STRUCTURE_OWNER, s.SITE_STATUS, s.STREAM, s.PROJECT_SF_ID, s.PROJECT_NAME, s.PROJECT_TYPE, s.SERVICE_LINE, s.CX_SP,
  s.ASSIGNED_DATE, s.SCOPING_FORECAST, s.SCOPING_ACTUAL, s.FBA_DATE, s.CURRENT_BOM_REV, 'ASSIGNED', CURRENT_TIMESTAMP(), 'sitetracker-sync');

MERGE INTO CORE.MILESTONE t
USING (
  SELECT m.ID AS MILESTONE_SF_ID, s.NAME AS SITE_ID, m.NAME, m.SEQUENCE__C AS SEQ, m.FORECAST_DATE__C AS FORECAST,
         m.ACTUAL_DATE__C AS ACTUAL, m.STATUS__C AS STATUS
  FROM RAW.ST_MILESTONE m JOIN RAW.ST_PROJECT p ON p.ID = m.PROJECT__C JOIN RAW.ST_SITE s ON s.ID = p.SITE__C
) s ON t.MILESTONE_SF_ID = s.MILESTONE_SF_ID
WHEN MATCHED THEN UPDATE SET SITE_ID = s.SITE_ID, NAME = s.NAME, SEQ = s.SEQ, FORECAST = s.FORECAST, ACTUAL = s.ACTUAL, STATUS = s.STATUS
WHEN NOT MATCHED THEN INSERT (MILESTONE_SF_ID, SITE_ID, NAME, SEQ, FORECAST, ACTUAL, STATUS)
  VALUES (s.MILESTONE_SF_ID, s.SITE_ID, s.NAME, s.SEQ, s.FORECAST, s.ACTUAL, s.STATUS);

SELECT SITE_ID, STREAM, CX_SP, WORKFLOW_STATE FROM CORE.SITE ORDER BY SITE_ID;
