-- =====================================================================================================
-- 09  Tasks: re-run the pipeline when site documents change, parse new PDFs, purge old application logs.
--     Tasks are created SUSPENDED in dev; resume them explicitly (bottom of file).
-- =====================================================================================================
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
USE WAREHOUSE IDENTIFIER($SCOPEIQ_WH);
USE SCHEMA APP;

SET WH_NAME = $SCOPEIQ_WH;
SET TASK_SCHEDULE = $SCOPEIQ_TASK_SCHEDULE;

-- Root task: only runs when the SITE_DOCS stage stream has new or changed files.
EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK APP.T_RUN_CHANGED_SITES WAREHOUSE = ' || $WH_NAME ||
  ' SCHEDULE = ''' || $TASK_SCHEDULE || '''' ||
  ' COMMENT = ''Run the ScopeIQ pipeline for sites with new or changed documents''' ||
  ' WHEN SYSTEM$STREAM_HAS_DATA(''RAW.SITE_DOCS_CHANGES'') AS CALL APP.SP_RUN_CHANGED_SITES()';

-- Child task: parse any new PDFs after the pipeline task (reuses 08 logic).
EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK APP.T_PARSE_NEW_PDFS WAREHOUSE = ' || $WH_NAME ||
  ' AFTER APP.T_RUN_CHANGED_SITES AS
  INSERT INTO RAW.DOC_PARSE (RELATIVE_PATH, SITE_ID, DOC_TYPE, MD5, PARSE_MODE, PARSED, PARSED_AT)
  SELECT f.RELATIVE_PATH, f.SITE_ID, f.DOC_TYPE, f.MD5, ''LAYOUT'',
         AI_PARSE_DOCUMENT(TO_FILE(''@RAW.SITE_DOCS'', f.RELATIVE_PATH), {''mode'': ''LAYOUT'', ''page_split'': true}), CURRENT_TIMESTAMP()
  FROM RAW.FILE_REGISTRY f
  LEFT JOIN RAW.DOC_PARSE d ON d.RELATIVE_PATH = f.RELATIVE_PATH AND d.PARSE_MODE = ''LAYOUT'' AND d.MD5 = f.MD5
  WHERE f.FILE_FORMAT = ''PDF'' AND f.DOC_TYPE IN (''CD'', ''RFDS'', ''MA_SA'') AND d.RELATIVE_PATH IS NULL';

-- Housekeeping: application logs are kept per environment (AUDIT_LOG and WORKFLOW_EVENT are never purged).
EXECUTE IMMEDIATE 'CREATE OR REPLACE TASK APP.T_PURGE_APP_LOG WAREHOUSE = ' || $WH_NAME ||
  ' SCHEDULE = ''USING CRON 30 2 * * * UTC'' AS
  DELETE FROM AUDIT.APP_LOG WHERE LOG_TS < DATEADD(day, -(SELECT COALESCE(MAX(TRY_TO_NUMBER(VALUE)), 30) FROM APP.SETTINGS WHERE KEY = ''APP_LOG_RETENTION_DAYS''), CURRENT_TIMESTAMP())';

MERGE INTO APP.SETTINGS t USING (SELECT 'APP_LOG_RETENTION_DAYS' AS KEY,
  CASE $SCOPEIQ_ENV WHEN 'dev' THEN '14' WHEN 'test' THEN '30' ELSE '90' END AS VALUE) s ON t.KEY = s.KEY
WHEN MATCHED THEN UPDATE SET VALUE = s.VALUE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (KEY, VALUE, UPDATED_AT) VALUES (s.KEY, s.VALUE, CURRENT_TIMESTAMP());

-- The owner needs EXECUTE TASK to resume tasks.
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);

-- Resume (child first, then root). In dev, leave suspended and use CALL APP.SP_RUN_PIPELINE(...) by hand.
ALTER TASK APP.T_PARSE_NEW_PDFS RESUME;
ALTER TASK APP.T_RUN_CHANGED_SITES RESUME;
ALTER TASK APP.T_PURGE_APP_LOG RESUME;
-- Run once now:  EXECUTE TASK APP.T_RUN_CHANGED_SITES;
-- History:       SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) WHERE NAME LIKE 'T_%' ORDER BY SCHEDULED_TIME DESC;
