-- =====================================================================================================
-- 10  Reporting views (APP schema, granted to the READ role): site status, open discrepancies, current BOM,
--     REV 0 -> REV n changes with reasons, estimates, workflow throughput, audit and errors.
-- =====================================================================================================
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
USE WAREHOUSE IDENTIFIER($SCOPEIQ_WH);

CREATE OR REPLACE VIEW APP.V_SITE_STATUS AS
SELECT s.SITE_ID, s.SITE_NAME, s.MARKET, s.STREAM, s.STRUCTURE_TYPE, s.HEIGHT_FT, s.CX_SP, s.WORKFLOW_STATE, s.ASSIGNED_TO,
       s.CURRENT_BOM_REV, s.SCOPING_FORECAST, r.STARTED_AT AS LAST_RUN_AT, r.STATUS AS LAST_RUN_STATUS,
       COUNT_IF(d.STATUS = 'OPEN') AS OPEN_DISCREPANCIES, COUNT_IF(d.SEVERITY = 'HIGH' AND d.STATUS NOT IN ('RESOLVED', 'CLOSED', 'DISMISSED')) AS HIGH_UNRESOLVED,
       COUNT(d.DISC_ID) AS TOTAL_DISCREPANCIES, e.CYCLE_DAYS, e.TOTAL_USD
FROM CORE.SITE s
LEFT JOIN CORE.PIPELINE_RUN r ON r.RUN_ID = s.LAST_RUN_ID
LEFT JOIN CORE.DISCREPANCY d ON d.SITE_ID = s.SITE_ID
LEFT JOIN CORE.ESTIMATE e ON e.SITE_ID = s.SITE_ID AND e.RUN_ID = s.LAST_RUN_ID
GROUP BY ALL;

CREATE OR REPLACE VIEW APP.V_DISCREPANCY_QUEUE AS
SELECT d.SITE_ID, d.DISC_ID, d.RULE_ID, d.SEVERITY, d.OUTCOME, d.STATUS, d.ASSIGNED_TO, d.REASON_CODE, d.TITLE,
       d.CREATED_AT, DATEDIFF(hour, d.CREATED_AT, CURRENT_TIMESTAMP()) AS AGE_HOURS
FROM CORE.DISCREPANCY d
WHERE d.STATUS NOT IN ('RESOLVED', 'CLOSED', 'DISMISSED');

CREATE OR REPLACE VIEW APP.V_BOM_CURRENT AS
SELECT b.SITE_ID, b.REV_LABEL, b.STATUS AS REV_STATUS, b.LOCKED, l.SECTOR, l.CATALOG_KEY, c.MODEL, c.DESCRIPTION, c.MANUFACTURER_PN AS MFR_PN,
       l.ACTION, l.DESIGN_QTY, l.SPARE_QTY, l.TOTAL_QTY, l.RULE_ID, l.REASON_CODE, l.SOURCE
FROM CORE.BOM_REVISION b
JOIN CORE.BOM_LINE l ON l.BOM_REV_ID = b.BOM_REV_ID
LEFT JOIN REF.MATERIAL_CATALOG c ON c.CATALOG_KEY = l.CATALOG_KEY
QUALIFY DENSE_RANK() OVER (PARTITION BY b.SITE_ID ORDER BY b.REV_NO DESC) = 1;

CREATE OR REPLACE VIEW APP.V_BOM_CHANGES AS
SELECT ch.SITE_ID, ch.SECTOR, ch.CATALOG_KEY, ch.ACTION, ch.FROM_QTY AS REV0_QTY, ch.TO_QTY AS REVN_QTY, ch.DELTA,
       r.VALUE:reason_code::VARCHAR AS REASON_CODE, r.VALUE:qty::NUMBER(18,2) AS REASON_QTY, ARRAY_TO_STRING(r.VALUE:disc_ids, ', ') AS DISC_IDS
FROM CORE.BOM_CHANGE ch, LATERAL FLATTEN(INPUT => ch.REASONS, OUTER => TRUE) r;

CREATE OR REPLACE VIEW APP.V_ESTIMATE AS
SELECT e.SITE_ID, e.CYCLE_DAYS, e.SERVICES_USD, e.MATERIAL_USD, e.TOTAL_USD, q.ACCESS_METHOD, q.CRANE_DAYS, q.MANLIFT_DAYS, q.RIGGING_CLASS, q.HOLD
FROM CORE.ESTIMATE e
JOIN CORE.SITE s ON s.SITE_ID = e.SITE_ID AND s.LAST_RUN_ID = e.RUN_ID
LEFT JOIN CORE.SITE_REQUIREMENT q ON q.SITE_ID = e.SITE_ID AND q.RUN_ID = e.RUN_ID;

CREATE OR REPLACE VIEW APP.V_WORKFLOW_THROUGHPUT AS
SELECT ENTITY_TYPE, FROM_STATE, ACTION, TO_STATE, ACTOR_ROLE, COUNT(*) AS EVENTS,
       MIN(EVENT_TS) AS FIRST_EVENT, MAX(EVENT_TS) AS LAST_EVENT
FROM WF.WORKFLOW_EVENT GROUP BY ALL;

CREATE OR REPLACE VIEW APP.V_AUDIT_RECENT AS
SELECT EVENT_TS, SITE_ID, ENTITY_TYPE, ENTITY_ID, ACTION, ACTOR_USER_ID, ACTOR_ROLE, REASON_CODE, COMMENT, CORRELATION_ID
FROM AUDIT.AUDIT_LOG WHERE EVENT_TS > DATEADD(day, -30, CURRENT_TIMESTAMP());

CREATE OR REPLACE VIEW APP.V_ERRORS_24H AS
SELECT ERROR_TS, ERROR_CODE, MESSAGE, EXCEPTION_TYPE, WHERE_RAISED, SITE_ID, USER_ID, CORRELATION_ID
FROM AUDIT.ERROR_LOG WHERE ERROR_TS > DATEADD(hour, -24, CURRENT_TIMESTAMP());

GRANT SELECT ON ALL VIEWS IN SCHEMA APP TO ROLE IDENTIFIER($SCOPEIQ_READ_ROLE);
