"""Generate the schema-driven Snowflake scripts from scopeiq/db/schema.py (single source of truth), export the
local pipeline results for loading, and package the code for the Snowpark procedures.

    python scripts/generate_snowflake_sql.py              # regenerate 03/04/05 + seed export + code zip
    python scripts/generate_snowflake_sql.py --no-seed    # skip the pipeline-results export

Writes (under code/):
    snowflake/03_tables.sql               CREATE TABLE for RAW, REF, CORE, WF, AUDIT
    snowflake/04_load_sitetracker.sql     COPY SiteTracker CSVs into RAW.ST_*
    snowflake/05_load_reference.sql       COPY reference_data/*.csv into REF.*
    snowflake/seed/<LAYER>.<TABLE>.json   NDJSON of the local database (pipeline results, stored redlines)
    snowflake/11_load_pipeline_results.sql
    dist/scopeiq_code.zip                 backend/scopeiq + reference_data, imported by the procedures
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scopeiq.config import get_settings  # noqa: E402
from scopeiq.db.ddl import snowflake_ddl  # noqa: E402
from scopeiq.db.schema import REF_TABLE_FILES, get_table, tables  # noqa: E402

CODE = Path(__file__).resolve().parents[2]
SF = CODE / "snowflake"
HEADER = """-- =====================================================================================================
-- {title}
-- GENERATED by backend/scripts/generate_snowflake_sql.py from scopeiq/db/schema.py - do not edit by hand.
-- =====================================================================================================
USE ROLE IDENTIFIER($SCOPEIQ_ADMIN_ROLE);
USE DATABASE IDENTIFIER($SCOPEIQ_DB);
USE WAREHOUSE IDENTIFIER($SCOPEIQ_WH);

"""
ST_FILES = {"ST_SITE": "Site.csv", "ST_PROJECT": "Project.csv", "ST_MILESTONE": "Milestone.csv", "ST_DOCUMENT": "Document.csv"}
RESULT_LAYERS = ("CORE", "WF", "AUDIT")


def tables_sql() -> str:
    return HEADER.format(title="03  Tables for every layer (RAW, REF, CORE, WF, AUDIT). Idempotent (IF NOT EXISTS).") + snowflake_ddl()


def _copy(t, stage_path: str, extra: list[str]) -> str:
    cols = [c for c in t.column_names if c not in ("LOADED_AT", "LOADED_BY")]
    sel = ", ".join(f"${i + 1}" for i in range(len(cols)))
    tgt = ", ".join(cols + extra)
    ext = {"LOADED_AT": "CURRENT_TIMESTAMP()", "LOADED_BY": "CURRENT_USER()"}
    return (f"TRUNCATE TABLE {t.fqn};\n"
            f"COPY INTO {t.fqn} ({tgt})\n  FROM (SELECT {sel}, {', '.join(ext[e] for e in extra)} FROM {stage_path})\n"
            f"  FILE_FORMAT = (FORMAT_NAME = 'RAW.CSV_SKIP_HEADER') ON_ERROR = 'ABORT_STATEMENT';\n\n")


def sitetracker_sql() -> str:
    out = [HEADER.format(title="04  Load the SiteTracker exports (stage Input-Data/SiteTracker/*.csv) into RAW.ST_*.")]
    for name, file in ST_FILES.items():
        out.append(_copy(get_table(f"RAW.{name}"), f"@RAW.SITE_DOCS/Input-Data/SiteTracker/{file}", ["LOADED_AT"]))
    out.append("SELECT 'ST_SITE' AS T, COUNT(*) AS N FROM RAW.ST_SITE UNION ALL SELECT 'ST_PROJECT', COUNT(*) FROM RAW.ST_PROJECT\n"
               "UNION ALL SELECT 'ST_MILESTONE', COUNT(*) FROM RAW.ST_MILESTONE UNION ALL SELECT 'ST_DOCUMENT', COUNT(*) FROM RAW.ST_DOCUMENT;\n")
    return "".join(out)


def reference_sql() -> str:
    out = [HEADER.format(title="05  Load the reference library (stage SCOPEIQ_CODE/reference_data/*.csv) into REF.*.\n"
                               "--     Re-run after editing a CSV; rows carry VERSION / EFFECTIVE_FROM / EFFECTIVE_TO / ACTIVE.")]
    for name, file in REF_TABLE_FILES.items():
        out.append(_copy(get_table(f"REF.{name}"), f"@RAW.SCOPEIQ_CODE/reference_data/{file}", ["LOADED_AT", "LOADED_BY"]))
    out.append("SELECT TABLE_NAME, ROW_COUNT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'REF' ORDER BY 1;\n")
    return "".join(out)


def export_results(db_path: Path) -> list[tuple[str, int]]:
    """NDJSON per CORE/WF/AUDIT table from the local SQLite database; JSON columns become real objects."""
    seed = SF / "seed"
    seed.mkdir(parents=True, exist_ok=True)
    for old in seed.glob("*.json"):
        old.unlink()
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    counts = []
    for t in [t for lyr in RESULT_LAYERS for t in tables(lyr) if t.fqn not in ("AUDIT.APP_LOG", "AUDIT.ERROR_LOG")]:
        rows = con.execute(f"SELECT * FROM {t.layer}__{t.name}").fetchall()
        if not rows:
            continue
        types = {c.name: c.type for c in t.columns}
        with open(seed / f"{t.fqn}.json", "w", encoding="utf-8") as f:
            for r in rows:
                rec = {}
                for k in r.keys():
                    v = r[k]
                    if v is not None and types.get(k) == "V":
                        try:
                            v = json.loads(v)
                        except (TypeError, ValueError):
                            pass
                    elif v is not None and types.get(k) == "B":
                        v = bool(v)
                    rec[k] = v
                f.write(json.dumps(rec, default=str) + "\n")
        counts.append((t.fqn, len(rows)))
    return counts


def results_sql(counts: list[tuple[str, int]]) -> str:
    out = [HEADER.format(title="11  Load pipeline results produced locally (stored discrepancies, redlines, RFIs, BOM revisions,\n"
                               "--     estimates, workflow and audit) so the app has data before the first Snowflake run.\n"
                               "--     PUT needs the Snowflake CLI / SnowSQL / deploy_snowflake.py (not a worksheet):\n"
                               "--       snow stage copy snowflake/seed @<DB>.RAW.SEED --overwrite")]
    for fqn, n in counts:
        t = get_table(fqn)
        out.append(f"-- {n} rows\nDELETE FROM {fqn};\nCOPY INTO {fqn} FROM @RAW.SEED/{fqn}.json\n"
                   f"  FILE_FORMAT = (FORMAT_NAME = 'RAW.NDJSON') MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE ON_ERROR = 'ABORT_STATEMENT';\n\n")
        _ = t
    out.append("SELECT 'CORE.DISCREPANCY' AS T, COUNT(*) AS N FROM CORE.DISCREPANCY UNION ALL SELECT 'CORE.REDLINE', COUNT(*) FROM CORE.REDLINE\n"
               "UNION ALL SELECT 'CORE.BOM_LINE', COUNT(*) FROM CORE.BOM_LINE;\n")
    return "".join(out)


def package_code() -> Path:
    dist = CODE / "dist"
    dist.mkdir(exist_ok=True)
    z = dist / "scopeiq_code.zip"
    with zipfile.ZipFile(z, "w", zipfile.ZIP_DEFLATED) as zf:
        for base in (CODE / "backend" / "scopeiq", CODE / "reference_data"):
            for p in sorted(base.rglob("*")):
                if p.is_file() and "__pycache__" not in p.parts:
                    zf.write(p, p.relative_to(CODE).as_posix())
    return z


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-seed", action="store_true")
    args = ap.parse_args()
    (SF / "03_tables.sql").write_text(tables_sql(), encoding="utf-8")
    (SF / "04_load_sitetracker.sql").write_text(sitetracker_sql(), encoding="utf-8")
    (SF / "05_load_reference.sql").write_text(reference_sql(), encoding="utf-8")
    print("wrote 03_tables.sql, 04_load_sitetracker.sql, 05_load_reference.sql")
    if not args.no_seed:
        db = get_settings().path("database.sqlite_path")
        counts = export_results(db) if db.exists() else []
        (SF / "11_load_pipeline_results.sql").write_text(results_sql(counts), encoding="utf-8")
        print(f"exported {sum(n for _, n in counts)} rows from {len(counts)} tables to snowflake/seed/")
    print(f"packaged {package_code()}")


if __name__ == "__main__":
    main()
